/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemperpustakaan;

import java.sql.*;
import javax.swing.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author INDRA L GHAZALI
 */
public class Calon_Anggota extends javax.swing.JFrame {
    private Connection conec;
    

    /**
     * Creates new form Calon_Anggota
     */
    private void tabs(){
        String sql="select * from anggota";
        DefaultTableModel ax=new DefaultTableModel();
        ax.addColumn("ID_Pendaftar");
        ax.addColumn("NIP_NIS");
        ax.addColumn("Nama");
        ax.addColumn("Tempat_Lahir");
        ax.addColumn("Tgl_Lahir");
        ax.addColumn("Jenis_Kelamin");
        ax.addColumn("Agama");
        ax.addColumn("Jurusan");
        ax.addColumn("Alamat");
        ax.addColumn("Status");
        
        tblanggota.setModel(ax);
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                
                ax.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
                System.out.println("koneksi sukses");

        }

        }
        catch(Exception e){
            System.out.println("Err koneksi gagal");
        }   
        }
    
    public Calon_Anggota() {
        initComponents();
        koneksiDatabase();
        nomoran();
        tabs();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tblsave = new javax.swing.JButton();
        tbledit = new javax.swing.JButton();
        tblcancel = new javax.swing.JButton();
        tblsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblanggota = new javax.swing.JTable();
        tfidpen = new javax.swing.JTextField();
        tfnama = new javax.swing.JTextField();
        tftempat = new javax.swing.JTextField();
        tftgl = new javax.swing.JTextField();
        cbjenkel = new javax.swing.JComboBox();
        tfagama = new javax.swing.JTextField();
        tfjurusan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfalamat = new javax.swing.JTextArea();
        cbstatus = new javax.swing.JComboBox();
        tbldelete = new javax.swing.JButton();
        tblriset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tfnip = new javax.swing.JTextField();
        tfcari = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Anggota"));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRY DATA ANGGOTA");

        jLabel2.setText("ID_Pendaftar");

        jLabel3.setText("Nama");

        jLabel4.setText("Tempat_lahir");

        jLabel5.setText("Tgl_Lahir");

        jLabel6.setText("Jenis_Kelamin");

        jLabel7.setText("Agama");

        jLabel8.setText("Jurusan");

        jLabel9.setText("Alamat");

        jLabel10.setText("Status");

        tblsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SAVE.jpg"))); // NOI18N
        tblsave.setText("Save");
        tblsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsaveActionPerformed(evt);
            }
        });

        tbledit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        tbledit.setText("Edit");
        tbledit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbleditActionPerformed(evt);
            }
        });

        tblcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close.jpg"))); // NOI18N
        tblcancel.setText("Cancel");
        tblcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblcancelActionPerformed(evt);
            }
        });

        tblsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchtext.png"))); // NOI18N
        tblsearch.setText("Search");
        tblsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsearchActionPerformed(evt);
            }
        });

        tblanggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Pendaftar", "Nama", "Tempat_Lahir", "Tgl_Lahir", "Jenis_Kelamin", "Agama", "Jurusan", "Alamat", "Status"
            }
        ));
        tblanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblanggotaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblanggota);

        cbjenkel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "::Pilih Jenkel::", "Laki-Laki", "Perempuan" }));

        tfalamat.setColumns(20);
        tfalamat.setRows(5);
        jScrollPane2.setViewportView(tfalamat);

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "::Pilih Status::", "Siswa", "Guru" }));

        tbldelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete16.gif"))); // NOI18N
        tbldelete.setText("Delete");
        tbldelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbldeleteActionPerformed(evt);
            }
        });

        tblriset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ITransaksi.png"))); // NOI18N
        tblriset.setText("Reset");
        tblriset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblrisetActionPerformed(evt);
            }
        });

        jLabel11.setText("NIP_NIS");

        tfcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcariKeyReleased(evt);
            }
        });

        jLabel12.setText("Cari berdasarkan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbjenkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tftgl, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tftempat, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfnip, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tblsave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbledit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbldelete))
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfidpen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfagama, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tblcancel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tblriset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tblsearch))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfcari, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfidpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tfagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tftempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tftgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(31, 31, 31))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbjenkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblsave)
                    .addComponent(tbledit)
                    .addComponent(tbldelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblcancel)
                    .addComponent(tblriset)
                    .addComponent(tblsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsaveActionPerformed
        // TODO add your handling code here:
        String vid   = tfidpen.getText();
        String vnip  = tfnip.getText();
        String namz  = tfnama.getText();
        String tempat= tftempat.getText();
        String tgl   = tftgl.getText();
        String jenkel=(String)cbjenkel.getSelectedItem().toString();
        String agama = tfagama.getText();
        String jurus = tfjurusan.getText();
        String alamat= tfalamat.getText();
        String status =(String)cbstatus.getSelectedItem().toString();
        
        
        if(tfnama.getText().trim().equals("") && tfnip.getText().trim().equals("")){
            JOptionPane.showMessageDialog(
                null,"Data belum lengkap !!!");}
        else{
            try {java.sql.Statement stat=conec.createStatement();
                ResultSet data=stat.executeQuery("SELECT *FROM anggota WHERE ID_Pendaftar='"
                    +tfidpen.getText()+"'");
                if(data.next()){
                    JOptionPane.showMessageDialog(null,"Kode Sudah Digunakan");
                    tfidpen.requestFocus();
                }
                else{
                String sql = "INSERT INTO anggota VALUES('"+vid+"','"+vnip+"','"+namz+"','"+tempat+"','"+tgl+"','"+jenkel+"','"+agama+"','"+jurus+"','"+alamat+"','"+status+"')";
                stat.executeUpdate(sql);
                tfidpen.setText("");
                tfnip.setText("");
                tfnama.setText("");
                tftempat.setText("");
                tftgl.setText("");
                cbjenkel.setSelectedIndex(0);
                tfagama.setText("");
                tfjurusan.setText("");
                tfalamat.setText("");
                cbstatus.setSelectedIndex(0);
                tfidpen.requestFocus();  
                
                }
                nomoran();
                stat.close();
            }
            
            catch(Exception a){
            JOptionPane.showMessageDialog(null,"TERJADI KESALAHAN "+a);
            }
        tabs();
        }    
    }//GEN-LAST:event_tblsaveActionPerformed

    private void tblanggotaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblanggotaMouseReleased
        // TODO add your handling code here:
        int baris = tblanggota.getSelectedRow();
        int kolom = tblanggota.getSelectedColumn();
        String dataTerpilih = tblanggota.getValueAt(baris, kolom).toString();
        String kolom1 = tblanggota.getValueAt(baris, 0).toString();
        String kolom2 = tblanggota.getValueAt(baris, 1).toString();
        String kolom3 = tblanggota.getValueAt(baris, 2).toString();
        String kolom4 = tblanggota.getValueAt(baris, 3).toString();
        String kolom5 = tblanggota.getValueAt(baris, 4).toString();
        String kolom6 = tblanggota.getValueAt(baris, 5).toString();
        String kolom7 = tblanggota.getValueAt(baris, 6).toString();
        String kolom8 = tblanggota.getValueAt(baris, 7).toString();
        String kolom9 = tblanggota.getValueAt(baris, 8).toString();
        String kolom10 = tblanggota.getValueAt(baris, 9).toString();
        tfidpen.setText(kolom1);
        tfnip.setText(kolom2); 
        tfnama.setText(kolom3);        
        tftempat.setText(kolom4);
        tftgl.setText(kolom5);
        cbjenkel.setSelectedItem(kolom6);
        tfagama.setText(kolom7);
        tfjurusan.setText(kolom8);
        tfalamat.setText(kolom9);
        cbstatus.setSelectedItem(kolom10);
    }//GEN-LAST:event_tblanggotaMouseReleased

    private void tbleditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbleditActionPerformed
        // TODO add your handling code here:
        String sql="update anggota set NIP_NIS='"+tfnip.getText()+"',"
                + "Nama='"+tfnama.getText()+"',"
                + "Tempat_Lahir='"+tftempat.getText()+"',"
                + "Tgl_Lahir='"+tftgl.getText()+"',"
                + "Jenis_Kelamin='"+cbjenkel.getSelectedItem()+"',"
                + "Agama='"+tfagama.getText()+"',"
                + "Jurusan='"+tfjurusan.getText()+"',"
                + "Alamat='"+tfalamat.getText()+"',"
                + "Status='"+cbstatus.getSelectedItem()+"'"
                + "where ID_Pendaftar='"+tfidpen.getText().trim()+"'";
        if(tfidpen.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Data masih kosong!!","Edit Data",JOptionPane.WARNING_MESSAGE);
            tfidpen.requestFocus();
        }
        else{
            try{
                Statement stat=conec.createStatement();
                stat.executeUpdate(sql);
                stat.close();
                nomoran();
                //conec.close();
                tfidpen.setText("");
                tfnip.setText("");
                tfnama.setText("");
                tftempat.setText("");
                tftgl.setText("");
                cbjenkel.setSelectedIndex(0);
                tfagama.setText("");
                tfjurusan.setText("");
                tfalamat.setText("");
                cbstatus.setSelectedIndex(0);
                tfidpen.requestFocus();
                
                nomoran();
                stat.close();
            }
            catch(Exception exc)  {
                System.err.println( "Error:"+exc);
            }
        }
        tabs();
    }//GEN-LAST:event_tbleditActionPerformed

    private void tbldeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbldeleteActionPerformed
        // TODO add your handling code here:
        String sql="delete from anggota where ID_Pendaftar='"+tfidpen.getText().trim()+"'";
        if(tfidpen.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "kode masih kosong !","Hapus Data",JOptionPane.WARNING_MESSAGE);
            tfidpen.requestFocus();
        }
        else
        {
            try
            {
                Statement stat=conec.createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data sudah dihapus","Hapus Data",JOptionPane.WARNING_MESSAGE);
                stat.close();
                tfidpen.setText("");
                tfnip.setText("");
                tfnama.setText("");
                tftempat.setText("");
                tftgl.setText("");
                cbjenkel.setSelectedIndex(0);
                tfagama.setText("");
                tfjurusan.setText("");
                tfalamat.setText("");
                cbstatus.setSelectedIndex(0);
                tfidpen.requestFocus();

                nomoran();
            }
            catch(Exception exc)
            {
                System.err.println(sql);
                System.err.println("Error : "+exc);
            }
        }
        tabs();
    }//GEN-LAST:event_tbldeleteActionPerformed

    private void tblcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tblcancelActionPerformed

    private void tblsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsearchActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM anggota WHERE ID_Pendaftar='"+tfidpen.getText()+"'";
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if(rs.next())
            {
                tfnip.setText(rs.getString(2));
                tfnama.setText(rs.getString(3));
                tftempat.setText(rs.getString(4));
                tftgl.setText(rs.getString(5));
                cbjenkel.setSelectedItem(rs.getString(6));
                tfagama.setText(rs.getString(7));
                tfjurusan.setText(rs.getString(8));
                tfalamat.setText(rs.getString(9));
                cbstatus.setSelectedItem(rs.getString(10));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "kode tidak ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                tfidpen.requestFocus();
            }
            stat.close();
        }
        catch(Exception exc){
            System.err.println("Terjadi kesalahan : "+exc);
        }
    }//GEN-LAST:event_tblsearchActionPerformed

    private void tblrisetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblrisetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_tblrisetActionPerformed

    private void tfcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcariKeyReleased
        // TODO add your handling code here:
//        caritabel();
    }//GEN-LAST:event_tfcariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calon_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calon_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calon_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calon_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calon_Anggota().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbjenkel;
    private javax.swing.JComboBox cbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblanggota;
    private javax.swing.JButton tblcancel;
    private javax.swing.JButton tbldelete;
    private javax.swing.JButton tbledit;
    private javax.swing.JButton tblriset;
    private javax.swing.JButton tblsave;
    private javax.swing.JButton tblsearch;
    private javax.swing.JTextField tfagama;
    private javax.swing.JTextArea tfalamat;
    private javax.swing.JTextField tfcari;
    private javax.swing.JTextField tfidpen;
    private javax.swing.JTextField tfjurusan;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnip;
    private javax.swing.JTextField tftempat;
    private javax.swing.JTextField tftgl;
    // End of variables declaration//GEN-END:variables
    private void koneksiDatabase() {
       //throw new UnsupportedOperationException("Not yet implemented");
        try {Class.forName("com.mysql.jdbc.Driver");
        }
        catch(ClassNotFoundException cnf){}
        try {conec = DriverManager.getConnection("jdbc:mysql://localhost/sistemperpustakaan","root","");
        System.out.println("Koneksi Sukses");
                }
        catch(SQLException se){
            System.out.println("Koneksi Gagal : "+se);
        }
        catch(Exception e){}
    }
    
    private void nomoran() {
       // throw new UnsupportedOperationException("Not yet implemented");
        String sql = "select right (ID_Pendaftar,3) as no from anggota order by ID_Pendaftar asc";
        
        try {
            Statement pst = conec.prepareStatement(sql);
            Statement stat = conec.createStatement();
            ResultSet rs = pst.executeQuery(sql);
            if (rs.first()==false)
            {
                tfidpen.setText("ID001");
            }
            else {
                rs.last();
                int no = rs.getInt(1)+1;
                String kbinasi = String.valueOf(no);
                int p_kmbinasi = kbinasi.length();
                String zero = "";
                for(int i=0; i<3-p_kmbinasi;i++){
                   // kbinasi = "0"+kbinasi;
                    zero = zero+"0";
                }
                tfidpen.setText("ID"+zero+kbinasi);
            }
            rs.close();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan:"+e);
            
        }

    }

    private void reset() {
       // throw new UnsupportedOperationException("Not yet implemented");
               // tfidpen.setText("");
                tfnip.setText("");
                tfnama.setText("");
                tftempat.setText("");
                tftgl.setText("");
                cbjenkel.setSelectedItem("::Pilih Jenkel::");
                tfagama.setText("");
                tfjurusan.setText("");
                tfalamat.setText("");
                cbstatus.setSelectedItem("::Pilih Status::");
                tfidpen.requestFocus();
                
                nomoran();
    }

//    private void caritabel() {
//        //throw new UnsupportedOperationException("Not yet implemented");
//        String sql = "SELECT * FROM anggota where ID_Pendaftar like '%"+tfcari.getText()+"%' or NIP_NIS like '%"+tfcari.getText()+"%' or Nama like '%"+tfcari.getText()+"%'";
//        DefaultTableModel a = new DefaultTableModel();
//        a.addColumn("ID_Pendaftar");
//        a.addColumn("NIP_NIS");
//        a.addColumn("Nama");
//        a.addColumn("Tempat_Lahir");
//        a.addColumn("Tgl_Lahir");
//        a.addColumn("Jenis_Kelamin");
//        a.addColumn("Agama");
//        a.addColumn("Jurusan");
//        a.addColumn("alamat");
//        a.addColumn("Status");
//        tblanggota.setModel(a);
//        try {
//            Statement stat = conec.createStatement();
//            ResultSet rs=stat.executeQuery(sql);
//            while(rs.next()){
//                a.addRow(new Object[]{
//                    rs.getString("ID_Pendaftar"),
//                    rs.getString("NIP_NIS"),
//                    rs.getString("Nama"),
//                    rs.getString("Tempat_Lahir"),
//                    rs.getString("Tgl_Lahir"),
//                    rs.getString("Jenis_Kelamin"),
//                    rs.getString("Agama"),
//                    rs.getString("Jurusan"),
//                    rs.getString("alamat"),
//                    rs.getString("Status"),
//                });
//                    System.out.println("Tabel Sukses");
//            }
//        } catch (Exception e) {
//            System.out.println("Tabel Gagal");
//        }
//    }
    
}
