/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemperpustakaan;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author INDRA L GHAZALI
 */
public class Copy_Buku extends javax.swing.JFrame {
    DefaultTableModel DftTabMode;
    private Connection conec;

    /**
     * Creates new form Copybuku
     */
    
    public Copy_Buku() {
        initComponents();
        koneksiDatabase();
        nomoran();
        tampilData();
        setLocationRelativeTo(this);
        tfviewjudul.setWrapStyleWord(true);
        tfviewjudul.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfidcopy = new javax.swing.JTextField();
        tfidbuku = new javax.swing.JTextField();
        cbstatus = new javax.swing.JComboBox();
        tblsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablebuku = new javax.swing.JTable();
        tblsave = new javax.swing.JButton();
        tbledit = new javax.swing.JButton();
        tbldelete = new javax.swing.JButton();
        tblcancel = new javax.swing.JButton();
        tblreset = new javax.swing.JButton();
        tfcari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfviewjudul = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Copy Buku"));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRY DATA COPY BUKU");

        jLabel2.setText("ID Copy Buku");

        jLabel5.setText("ID Buku");

        jLabel6.setText("Status Buku");

        tfidbuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfidbukuKeyPressed(evt);
            }
        });

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ada", "Terpinjam" }));

        tblsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchtext.png"))); // NOI18N
        tblsearch.setText("Search");
        tblsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsearchActionPerformed(evt);
            }
        });

        tablebuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablebuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablebukuMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablebuku);

        tblsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SAVE.jpg"))); // NOI18N
        tblsave.setText("Save");
        tblsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsaveActionPerformed(evt);
            }
        });

        tbledit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        tbledit.setText("Edit");
        tbledit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbleditActionPerformed(evt);
            }
        });

        tbldelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete16.gif"))); // NOI18N
        tbldelete.setText("Delete");
        tbldelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbldeleteActionPerformed(evt);
            }
        });

        tblcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close.jpg"))); // NOI18N
        tblcancel.setText("Cancel");
        tblcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblcancelActionPerformed(evt);
            }
        });

        tblreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ITransaksi.png"))); // NOI18N
        tblreset.setText("Reset");
        tblreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblresetActionPerformed(evt);
            }
        });

        tfcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcariKeyReleased(evt);
            }
        });

        jLabel3.setText("Cari berdasarkan");

        tfviewjudul.setColumns(20);
        tfviewjudul.setRows(5);
        jScrollPane2.setViewportView(tfviewjudul);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tblsave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbledit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbldelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblcancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblreset))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfcari)
                                    .addComponent(cbstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfidcopy, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(tfidbuku))
                                        .addGap(18, 18, 18)
                                        .addComponent(tblsearch))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblsearch)
                    .addComponent(jLabel5)
                    .addComponent(tfidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfidcopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblsave)
                    .addComponent(tbledit)
                    .addComponent(tblcancel)
                    .addComponent(tbldelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblreset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsaveActionPerformed
        // TODO add your handling code here:
        String vkdbuku =tfidbuku.getText();
        String vjudul  =tfviewjudul.getText();
        String vcopy   =tfidbuku.getText()+tfidcopy.getText();
        String vkode   =tfidcopy.getText();
        if (tfidcopy.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Data belum lengkap !!!","PERHATIAN",JOptionPane.WARNING_MESSAGE);
            tfidcopy.requestFocus();
        }
        else {
            try {
                java.sql.Statement stat = conec.createStatement();
                ResultSet data=stat.executeQuery("SELECT * FROM copybuku WHERE ID_Copybuku='"+tfidcopy.getText()+"'");
                if (data.next()){
                    JOptionPane.showMessageDialog(null,"ID Buku sudah dimasukan","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                    tfidcopy.requestFocus();
                }
                else {
                    String sql ="INSERT INTO copybuku VALUE('"+vkdbuku+"','"+vjudul+"','"+cbstatus.getSelectedItem()+"','"+vcopy+"','"+vkode+"')";
                    stat.executeUpdate(sql);
                    tfidbuku.setText("");
                    tfviewjudul.setText("");
                    tfidcopy.setText("");
                    tfidbuku.requestFocus();
                    tbledit.setEnabled(true);
                    tbldelete.setEnabled(true);

                tampilData();
                }
                
                stat.close();
            }
            catch(Exception exc){
                System.err.println("Terjadi kesalahan :"+exc);
            }
        }
    }//GEN-LAST:event_tblsaveActionPerformed

    private void tblsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsearchActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM Copybuku WHERE ID_Buku='"+tfidbuku.getText()+"'";
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if(rs.next())
            {
                tfviewjudul.setText(rs.getString(2));                
                cbstatus.setSelectedItem(rs.getString(3));
                tfidcopy.setText(rs.getString(5));
                //tfcopy.setText(rs.getString(4));
                String vid  = tfidbuku.getText();
                String sql2 = "SELECT * FROM buku WHERE ID_Buku='"+vid+"'";
                try{
                    Statement stat2=conec.createStatement();
                    ResultSet rs2=stat2.executeQuery(sql2);
                    if(rs2.next())
                    {
                        tfviewjudul.setText(rs2.getString(2));
                    }
                }
                catch(Exception exc){
                System.err.println("Terjadi kesalahan : "+exc);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "kode tidak ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
               tfidcopy.requestFocus();
            }
          stat.close();
        }
        catch(Exception exc){
            System.err.println("Terjadi kesalahan : "+exc);
        }
    }//GEN-LAST:event_tblsearchActionPerformed

    private void tbleditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbleditActionPerformed
        // TODO add your handling code here:
        String sql="update copybuku set ID_Copybuku='"+
        tfidcopy.getText()+"',Statusbuku='"+
        cbstatus.getSelectedItem()+"' where ID_Buku="+tfidbuku.getText();
        if (tfidbuku.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Kode Buku Masih Kosong","PERHATIAN",JOptionPane.WARNING_MESSAGE);
            tfidbuku.requestFocus();
        }
        else {
            try {
                Statement stat=conec.createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Sudah Di Edit");
                tfidbuku.setText("");
                tfviewjudul.setText("");
                tfidbuku.setText("");
                tfidbuku.requestFocus();
                stat.close();
                tampilData();
            }
        
            catch (Exception exc) {
                System.err.println(sql);
                System.err.println("Error : "+exc);
            }
        }
    }//GEN-LAST:event_tbleditActionPerformed

    private void tbldeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbldeleteActionPerformed
        // TODO add your handling code here:

        String id=tfidcopy.getText();
        String sql="delete from copybuku where Copy='"+id+"'";
        try{
            java.sql.Statement stat = conec.createStatement();
            stat.execute(sql);
            tfidbuku.setText("");
            tfviewjudul.setText("");
            tfidcopy.setText("");
            tfidbuku.setText("");
            tfidbuku.requestFocus();
            tampilData();
        }
        catch(Exception exc){
            System.out.println(exc);
        }
        
    }//GEN-LAST:event_tbldeleteActionPerformed

    private void tblcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tblcancelActionPerformed

    private void tablebukuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebukuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tablebukuMouseReleased

    private void tfidbukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfidbukuKeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            aaActionPerformed(new ActionEvent(evt.getSource(),evt.getID(),"KEY PRESS PROCESS"));
        }
    }//GEN-LAST:event_tfidbukuKeyPressed

    private void tblresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_tblresetActionPerformed

    private void tfcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcariKeyReleased
        // TODO add your handling code here:
        caritable();
    }//GEN-LAST:event_tfcariKeyReleased

    private void aaActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        String sql = "SELECT * FROM buku WHERE ID_Buku='"+tfidbuku.getText()+"'";
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if(rs.next())
            {
                tfviewjudul.setText(rs.getString(2));
                
                nomoran();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "kode tidak ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                tfidbuku.requestFocus();
                tfviewjudul.setText("");
            }
            stat.close();
        }
        catch(Exception exc){
            System.err.println("Terjadi kesalahan : "+exc);
        }
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Copy_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Copy_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Copy_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Copy_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Copy_Buku().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablebuku;
    private javax.swing.JButton tblcancel;
    private javax.swing.JButton tbldelete;
    private javax.swing.JButton tbledit;
    private javax.swing.JButton tblreset;
    private javax.swing.JButton tblsave;
    private javax.swing.JButton tblsearch;
    private javax.swing.JTextField tfcari;
    private javax.swing.JTextField tfidbuku;
    private javax.swing.JTextField tfidcopy;
    private javax.swing.JTextArea tfviewjudul;
    // End of variables declaration//GEN-END:variables

    private void koneksiDatabase() {
        //throw new UnsupportedOperationException("Not yet implemented");
              try {
            Class.forName("com.mysql.jdbc.Driver");
        }
        catch(ClassNotFoundException cnf){}
        try {conec = DriverManager.getConnection("jdbc:mysql://localhost/sistemperpustakaan","root","");
        System.out.println("Koneksi Sukses");
                }
        catch(SQLException se){
            System.out.println("Koneksi Gagal : "+se);
        }
        catch(Exception e){}
  
    }

    private void nomoran() {
       // throw new UnsupportedOperationException("Not yet implemented");
        
        try {     
          String sql1 = "select * from copybuku where ID_Copybuku like '"+tfidbuku.getText()+"%' order by Copy desc";
          java.sql.Statement stati = conec.createStatement();
          ResultSet rsa = stati.executeQuery(sql1);
          if (rsa.next()) {
                tfidcopy.setText(rsa.getString("Copy"));    
            }
            else {
          }
          
          String vcopy1 =tfidbuku.getText()+tfidcopy.getText();
          String sql = "select * from copybuku where ID_Copybuku='"+vcopy1+"' order by Copy desc";
          java.sql.Statement stat = conec.createStatement();  
          ResultSet rs = stat.executeQuery(sql);
            if (rs.next()) {
                String vidcopi  = rs.getString("Copy").substring(1);
                String an = "" + (Integer.parseInt(vidcopi) + 1);
                String Nol = "";

                if(an.length()==1)
                {Nol = "0";}
                else if(an.length()==2)
                {Nol = "";}
                tfidcopy.setText("" + Nol + an);
            } else {
             
                tfidcopy.setText("01");
                
                 
            }
           } catch (Exception exc) {
        	
        }
        
    }
        

    private void tampilData() {
        //throw new UnsupportedOperationException("Not yet implemented");
        Object[]Baris={"ID Copy Buku","Judul Buku","Status Buku"};
        DftTabMode=new DefaultTableModel(null,Baris);
        tablebuku.setModel(DftTabMode);
        String sql="select*from copybuku order by ID_Copybuku";
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            int total=0;
	    while(rs.next()){
                String tidbk=rs.getString("ID_Copybuku");
                String judl=rs.getString("Judul");
                String stt=rs.getString("Statusbuku");
                String[] data ={tidbk,judl,stt};
                DftTabMode.addRow(data);
            }
        }
           catch (Exception exc){
            System.err.println("Terjadi Kesalahan :"+exc);
            }
    }

    private void reset() {
       // throw new UnsupportedOperationException("Not yet implemented");
        tfidbuku.setText("");
        tfviewjudul.setText("");
        tfidcopy.setText("");
        tfidbuku.setText("");
        cbstatus.setSelectedItem("Ada");
        tfidbuku.requestFocus();
    }

    private void caritable() {
       // throw new UnsupportedOperationException("Not yet implemented");
        String sql = "SELECT * FROM copybuku where ID_Copybuku like '%"+tfcari.getText()+"%' or Judul like '%"+tfcari.getText()+"%'";
        DefaultTableModel a = new DefaultTableModel();
        a.addColumn("ID_Copybuku");
        a.addColumn("Judul");
        a.addColumn("Statusbuku");
        tablebuku.setModel(a);
        try {
            Statement stat = conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                a.addRow(new Object[]{
                    rs.getString("ID_Copybuku"),
                    rs.getString("Judul"),
                    rs.getString("Statusbuku"),
                });
                    System.out.println("Tabel Sukses");
            }
        } catch (Exception e) {
            System.out.println("Tabel Gagal");
        }
    }
}
