/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemperpustakaan;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author INDRA L GHAZALI
 */
public class Peminjaman extends javax.swing.JFrame {
    //DefaultTableModel DftTabMode;
    private Connection conec;
    private Statement stat;
    private ResultSet res;

    /**
     * Creates new form Peminjaman
     */
    
    private void tabs(){
        String sql="select * from peminjaman";
        DefaultTableModel ax=new DefaultTableModel();
        ax.addColumn("No_Pinjam");
        ax.addColumn("Tgl_Pinjam");
        ax.addColumn("Tglhrskembali");
        ax.addColumn("ID_Anggota");
        ax.addColumn("ID_Copybuku");
        ax.addColumn("Statusbuku");
        
        tabpeminjaman.setModel(ax);
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                
                ax.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)
                });
                System.out.println("koneksi sukses");

        }

        }
        catch(Exception e){
            System.out.println("Err koneksi gagal");
        }   
        }
    
    public Peminjaman() {
        initComponents();
        koneksiDatabase();
        //tampilData();
        time();
        tabs();
        nomoran();
        tfidang.requestFocus();
       // kembali();
        setLocationRelativeTo(this);
        tfjudul.setWrapStyleWord(true);
        tfjudul.setLineWrap(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tftglbalik = new javax.swing.JTextField();
        tfpinjam = new javax.swing.JTextField();
        tftgl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfidang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfnip = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfjenis = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfjudul = new javax.swing.JTextArea();
        tfidcopy = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabpeminjaman = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tblsave = new javax.swing.JButton();
        tblcancel = new javax.swing.JButton();
        tblsearch = new javax.swing.JButton();
        tblreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Peminjaman Buku"));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("No Pinjam");

        jLabel3.setText("Tgl Pinjam");

        jLabel4.setText("Tgl Harus Kembali");

        tftglbalik.setEnabled(false);

        tftgl.setEnabled(false);

        jLabel5.setText("ID Anggota");

        tfidang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidangActionPerformed(evt);
            }
        });
        tfidang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfidangKeyPressed(evt);
            }
        });

        jLabel9.setText("NIP/ NIS");

        tfnip.setEnabled(false);

        jLabel10.setText("Nama");

        tfnama.setEnabled(false);

        jLabel11.setText("Jenis Kelamin");

        tfjenis.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfnama)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfpinjam)
                            .addComponent(tftgl)
                            .addComponent(tftglbalik)
                            .addComponent(tfidang)
                            .addComponent(tfnip)
                            .addComponent(tfjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tftgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tftglbalik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfidang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("ID Copy Buku");

        jLabel7.setText("Judul");

        jLabel8.setText("Status");

        tfjudul.setColumns(20);
        tfjudul.setRows(5);
        tfjudul.setEnabled(false);
        jScrollPane2.setViewportView(tfjudul);

        tfidcopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidcopyActionPerformed(evt);
            }
        });

        a.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfidcopy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfidcopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabpeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabpeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabpeminjamanMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabpeminjaman);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PEMINJAMAN BUKU");

        tblsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SAVE.jpg"))); // NOI18N
        tblsave.setText("Save");
        tblsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsaveActionPerformed(evt);
            }
        });

        tblcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close.jpg"))); // NOI18N
        tblcancel.setText("Cancel");
        tblcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblcancelActionPerformed(evt);
            }
        });

        tblsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchtext.png"))); // NOI18N
        tblsearch.setText("Search");

        tblreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ITransaksi.png"))); // NOI18N
        tblreset.setText("Reset");
        tblreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tblsearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblsave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblreset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblcancel)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblreset)
                    .addComponent(tblsave))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int cc ;
    private void tabpeminjamanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabpeminjamanMouseReleased
        // TODO add your handling code here:
        int baris = tabpeminjaman.getSelectedRow();
        int kolom = tabpeminjaman.getSelectedColumn();
        String dataTerpilih = tabpeminjaman.getValueAt(baris, kolom).toString();
        String kolom1 = tabpeminjaman.getValueAt(baris, 0).toString();
        String kolom2 = tabpeminjaman.getValueAt(baris, 1).toString();
        String kolom3 = tabpeminjaman.getValueAt(baris, 2).toString();
        String kolom4 = tabpeminjaman.getValueAt(baris, 3).toString();
        String kolom5 = tabpeminjaman.getValueAt(baris, 4).toString();
        String kolom6 = tabpeminjaman.getValueAt(baris, 5).toString();
        tfpinjam.setText(kolom1);       
        tftgl.setText(kolom2);
        tftglbalik.setText(kolom3);
        tfidang.setText(kolom4);
        tfidcopy.setText(kolom5);
        a.setText(kolom6);
    }//GEN-LAST:event_tabpeminjamanMouseReleased

    private void tblcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tblcancelActionPerformed

    private void tblresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_tblresetActionPerformed

    private void tblsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsaveActionPerformed
        // TODO add your handling code here:
        //int cc = Integer.valueOf(tfpinjam.getText());
        String vnop  =tfpinjam.getText();
        String vcopy =tfpinjam.getText();
        String vtglp =tftgl.getText();
        String vtglk =tftglbalik.getText();
        String vkda  =tfidang.getText();
        String vidcopy =tfidcopy.getText();
        String hhh = a.getText();
               
        if (tfpinjam.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Data Masih Kosong!","PERHATIAN",JOptionPane.WARNING_MESSAGE);
            tfpinjam.requestFocus();
        }else if (tfidcopy.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Data Masih Kosong!","PERHATIAN",JOptionPane.WARNING_MESSAGE);
            tfidcopy.requestFocus();
        }
        
        if (a.getText().equals("Terpinjam")){
            JOptionPane.showMessageDialog(null,"Buku sudah terpinjam, silahkan cari buku lain","PERHATIAN",JOptionPane.WARNING_MESSAGE);
            tfidcopy.requestFocus();
        }else{
            try {
                java.sql.Statement stat = conec.createStatement();
                
                ResultSet data=stat.executeQuery("SELECT * FROM peminjaman WHERE No_Pinjam='"+tfpinjam.getText()+"'");
                if (data.next()){
                    JOptionPane.showMessageDialog(null,"No Pinjam sudah dimasukan","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                    tfpinjam.requestFocus();
                    
                
                }
                else {
                    String squ = "Update copybuku set Statusbuku='Terpinjam' "
                            + "where ID_Copybuku='"+tfidcopy.getText()+"'";
                    stat.executeUpdate(squ);
                    try {
                        //Statement stat=conec.createStatement();
                        String sql2 = "SELECT * FROM copybuku where ID_Copybuku='"+tfidcopy.getText()+"'" ;
                        ResultSet rp=stat.executeQuery(sql2);

                        if(rp.next()){
                            
                            String sql ="INSERT INTO peminjaman VALUE('"+vnop+"','"+vtglp+"','"+vtglk+"','"+vkda+"','"+vidcopy+"','"+rp.getString("Statusbuku")+"','"+cc+"')";
                            stat.executeUpdate(sql);

                        }else{
                            System.out.println("gagal");
                        }
                        }

                    catch(Exception exc){
                        System.err.println("Terjadi Kesalahan : "+exc);
                    }
                    
                    
                    
                    tfpinjam.setText("");
                    tfidang.setText("");
                    tfnip.setText("");
                    tfnama.setText("");
                    tfjenis.setText("");
                    tfidcopy.setText("");
                    tfjudul.setText("");
                    a.setText(""); 
                    //cc=0;
                    //tampilData();
                    time();
                    tabs();
                    {
                            
                	JOptionPane.showMessageDialog(null," Berhasil Di Simpan");
                        
		}
		    tfidang.requestFocus();
                }
                        
                stat.close();
            }
            catch(Exception exc){
                System.err.println("Terjadi kesalahan fatal :"+exc);
            }
            nomoran();
        }
    }//GEN-LAST:event_tblsaveActionPerformed

    private void tfidangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfidangKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            aaActionPerformed(new ActionEvent(evt.getSource(),evt.getID(),"KEY PRESS PROCESS"));
        }
    }//GEN-LAST:event_tfidangKeyPressed

    private void tfidcopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidcopyActionPerformed
        // TODO add your handling code here:
        try {
            Statement stat=conec.createStatement();
            String sql2 = "SELECT * FROM copybuku where ID_Copybuku='"+tfidcopy.getText()+"'" ;
            ResultSet rp=stat.executeQuery(sql2);
            
            if(rp.next()){
                a.setText(rp.getString("Statusbuku"));
                tfjudul.setText(rp.getString("Judul"));
                
                
            }else{
                JOptionPane.showMessageDialog(null,"ID Copy Buku Tidak Ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                tfidcopy.requestFocus();
                tfjudul.setText("");
            }
    //    if(rp.next()){
    //    cbstatus.setSelectedItem(rp.getString("Statusbuku"));    
    //    if(cbstatus.getSelectedItem().equals("Terpinjam"))
//				{
//					JOptionPane.showMessageDialog(null,"Buku Sedang Dipinjam");
//				}        
//        String sql="SELECT * FROM copybuku WHERE ID_Copybuku='"+tfidcopy.getText()+"'";
//        ResultSet rs = stat.executeQuery(sql);
                    
//            if (rs.next()) {
//                tfjudul.setText(rs.getString(2));
                
//            }
  //          else {
  //              JOptionPane.showMessageDialog(null,"ID Copy Buku Tidak Ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
   //             tfidcopy.requestFocus();
   //             tfjudul.setText("");
            
   //         }
     //       stat.close();
       //         }
            }
        
        catch(Exception exc){
            System.err.println("Terjadi Kesalahan : "+exc);
        }
        nomoran();
    }//GEN-LAST:event_tfidcopyActionPerformed

    private void tfidangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peminjaman().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabpeminjaman;
    private javax.swing.JButton tblcancel;
    private javax.swing.JButton tblreset;
    private javax.swing.JButton tblsave;
    private javax.swing.JButton tblsearch;
    private javax.swing.JTextField tfidang;
    private javax.swing.JTextField tfidcopy;
    private javax.swing.JTextField tfjenis;
    private javax.swing.JTextArea tfjudul;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnip;
    private javax.swing.JTextField tfpinjam;
    private javax.swing.JTextField tftgl;
    private javax.swing.JTextField tftglbalik;
    // End of variables declaration//GEN-END:variables

    private void koneksiDatabase() {
        //throw new UnsupportedOperationException("Not yet implemented");
              try {
            Class.forName("com.mysql.jdbc.Driver");
        }
        catch(ClassNotFoundException cnf){}
        try {conec = DriverManager.getConnection("jdbc:mysql://localhost/sistemperpustakaan","root","");
        System.out.println("Koneksi Sukses");
                }
        catch(SQLException se){
            System.out.println("Koneksi Gagal : "+se);
        }
        catch(Exception e){}
  
    }

    private void nomoran() {
        //throw new UnsupportedOperationException("Not yet implemented");
        String vtfidang = tfidang.getText(); 
        String sql = "select right (No_Pinjam,2) as no from peminjaman where No_Pinjam like '"+tfidang.getText()+"%' order by No_Pinjam asc";
        
        try {
            Statement pst = conec.prepareStatement(sql);
            Statement stat = conec.createStatement();
            ResultSet rs = pst.executeQuery(sql);
            if (rs.first()==false)
            {
                tfpinjam.setText(vtfidang + "01");
                cc=1;
            }
            else {
                rs.last();
                int no = rs.getInt(1)+1;
                String kbinasi = String.valueOf(no);
                int pjg_kbinasi = kbinasi.length();
                String jebot = "";
                for(int i=0; i<2-pjg_kbinasi;i++){
                   // kbinasi = "0"+kbinasi;
                    jebot = jebot+"0";
                }
                tfpinjam.setText(vtfidang+jebot+kbinasi);
                cc = Integer.parseInt(kbinasi);
            }
            rs.close();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan fatal2 :"+e);
            
        }
    }
    
    private void nomoran2() {
       try {      
          String vtfidang = tfidang.getText(); 
          String sql1 = "select * from peminjaman where No_Pinjam like '"+tfidang.getText()+"%' order by Pinjam desc";
          java.sql.Statement stati = conec.createStatement();
          ResultSet rsa = stati.executeQuery(sql1);
          if (rsa.next()) {
                tfpinjam.setText(rsa.getString("No_Pinjam"));    
            }
            else {
          }
          
          String vcopy1 =tfidang.getText()+tfpinjam.getText();
          String sql = "select * from peminjaman where No_Pinjam like '"+vtfidang+"%' order by Pinjam desc";
          java.sql.Statement stat = conec.createStatement();  
          ResultSet rs = stat.executeQuery(sql);
            if (rs.next()) {
                String vidcopi  = rs.getString("Pinjam").substring(1);
                String an = "" + (Integer.parseInt(vidcopi) + 1);
                String Nol = "";
                String gab="";

                if(an.length()==1)
                {Nol = "0";}
                else if(an.length()==2)
                {Nol = "";}
                tfpinjam.setText(vtfidang+ "" + Nol + an);
                gab=("" + Nol + an);
                cc= Integer.valueOf(gab);
            } else {
             
                tfpinjam.setText(vtfidang + "01");
                
                 
            }
           } catch (Exception exc) {
        	
        }

    }

    private void reset() {
        //throw new UnsupportedOperationException("Not yet implemented");
               
        //tftgl.setText("");
        //tftglbalik.setText("");
        tfidang.setText("");
        tfnip.setText("");
        tfnama.setText("");
        tfjenis.setText("");
        tfidcopy.setText("");
        tfjudul.setText("");
        a.setText("");
        tfpinjam.requestFocus();
    }

/*    private void cbbuku() {
       // throw new UnsupportedOperationException("Not yet implemented");
        String sql="select ID_Copybuku from copybuku";
       try {
           //cbpasien.removeAllItems();
           Statement stat = conec.createStatement();
           ResultSet rs = stat.executeQuery(sql);
           while(rs.next()){
               String vidk = rs.getString("ID_Copybuku");
               tfidcopy.addItem(vidk);
               
           }
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Terjadi Kesalahan :"+e);
       }
    }*/

    private void aaActionPerformed(ActionEvent actionEvent) {
        //throw new UnsupportedOperationException("Not yet implemented");
        String vid_kartu=tfidang.getText();
        String vid_anggota ;
        String sql="SELECT * FROM kartu WHERE ID_Anggota = '" + vid_kartu + "'";
        try{
            Statement stat = conec.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){                
                vid_anggota=rs.getString("ID_Pendaftar");
                String sql2="SELECT * FROM anggota WHERE ID_Pendaftar = '" + vid_anggota + "'";
                try{
                    Statement stat2 = conec.createStatement();
                    ResultSet rs2 = stat2.executeQuery(sql2);
                    if(rs2.next()){               
              
                           tfnip.setText(rs2.getString(2));
                           tfnama.setText(rs2.getString(3));
                           tfjenis.setText(rs2.getString(6));
                           tfidcopy.requestFocus();
             
                     
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Terjadi kesalahan:"+e);
                }
                nomoran(); 
                    }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan:"+e);
        }
        /*String sql = "SELECT * FROM kartu WHERE ID_Anggota='"+tfidang.getText()+"'";
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if(rs.next())
            {
                tfnip.setText(rs.getString(2));
                tfnama.setText(rs.getString(3));
                tfjenis.setText(rs.getString(6));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "ID Anggota tidak ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                tfidang.requestFocus();
                tfnip.setText("");
                tfnama.setText("");
                tfjenis.setText("");
            }
            stat.close();
        }
        catch(Exception exc){
            System.err.println("Terjadi kesalahan : "+exc);
        }*/
    }

    /*private void kembali() {
        //throw new UnsupportedOperationException("Not yet implemented");
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try{

        //Konversi dari string ke tanggal
        Date TanggalPinjam =df.parse(tftgl.getText());
        Date TanggalKembali = df.parse(tftglbalik.getText());

        //Tgl di konversi ke milidetik
        long Hari1 = TanggalPinjam.getTime();
        long Hari2 = TanggalKembali.getTime();
        long diff = Hari2 - Hari1;
        long Lama = diff / (24 * 60 * 60 * 1000);

        tf.setText(Long.toString(Lama));
        } catch (ParseException e)
        {
        e.printStackTrace();
        }
}

    }*/

    /*private void tampilData() {
       // throw new UnsupportedOperationException("Not yet implemented");
        Object[]Baris={"No Pinjam","Tgl Pinjam","Tgl Harus Kembali","ID Anggota","ID Copy Buku","Status Buku"};
        DftTabMode=new DefaultTableModel(null,Baris);
        tabpeminjaman.setModel(DftTabMode);
        String sql="select * from peminjaman";
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            int total=0;
	    while(rs.next()){
                String tnop=rs.getString("No_Pinjam");
                String ttglp=rs.getString("Tgl_Pinjam");
                String ttglk=rs.getString("Tgl_hrskembali");
                String tanggota=rs.getString("ID_Anggota");
                String tcopybk=rs.getString("ID_Copybuku");
                String tstt=rs.getString("Statusbuku");
                String[] data ={tnop,ttglp,ttglk,tanggota,tcopybk,tstt};
                DftTabMode.addRow(data);
                
            }
        }
           catch (Exception exc){
            System.err.println("Terjadi Kesalahan :"+exc);
            }
    }*/

    private void time() {
        //throw new UnsupportedOperationException("Not yet implemented");
        Calendar cal = Calendar.getInstance();
	SimpleDateFormat now = new SimpleDateFormat("dd-MMM-yyyy");
        String sekarng = now.format(cal.getTime());
        tftgl.setText(sekarng);
	cal.add(Calendar.DATE,7);
	Date Hari7 = cal.getTime();
        String hrskembali = now.format(cal.getTime());
        tftglbalik.setText(hrskembali);
    }
}

        //SimpleDateFormat sdf;
        //sdf = new SimpleDateFormat("yyyy-M-d");
        //tftglbalik.setText(sdf.format(tftgll.getDate()));