/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemperpustakaan;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author INDRA L GHAZALI
 */
public class Pengembalian extends javax.swing.JFrame {
    DefaultTableModel DftTabMode;
    private Connection conec ;

    /**
     * Creates new form Pengembalian
     */
    public Pengembalian() {
        initComponents();
        koneksiDatabase();
        //time();
        tampilData();
        //carianggota();
        caribuku();
        jenis();
        pinjam();
        nomoran();
        tfidcopy.requestFocus();
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat now = new SimpleDateFormat("dd-MMM-yyyy");
        String date = now.format(cal.getTime());
        tftglbalik.setText(date);
        
        tftotal.setText("0");
        
        setLocationRelativeTo(this);
        tfjudul.setWrapStyleWord(true);
        tfjudul.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfnokembali = new javax.swing.JTextField();
        tftglbalik = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfnopinjam = new javax.swing.JTextField();
        tftglpinjam = new javax.swing.JTextField();
        tftglhrsbalik = new javax.swing.JTextField();
        tfterlambat = new javax.swing.JTextField();
        tfkddenda = new javax.swing.JTextField();
        tfjumlahbiaya = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tftotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfnamajenis = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabkembali = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfidcopy = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfjudul = new javax.swing.JTextArea();
        cbstatus = new javax.swing.JComboBox();
        tblsave = new javax.swing.JButton();
        tblreset = new javax.swing.JButton();
        tblcancel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfidang = new javax.swing.JTextField();
        tfviewnama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Pengembalian Buku"));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("No Kembali");

        jLabel3.setText("Tgl Kembali");

        tfnokembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnokembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfnokembali, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftglbalik, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnokembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftglbalik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("No Pinjam");

        jLabel5.setText("Tgl Pinjam");

        jLabel6.setText("Tgl Harus Kembali");

        jLabel9.setText("KD Denda");

        jLabel10.setText("Jumlah Biaya Denda");

        jLabel11.setText("Keterlambatan");

        jLabel12.setText("Nama Jenis Denda");

        tfterlambat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfterlambatActionPerformed(evt);
            }
        });

        jLabel16.setText("Total");

        jLabel17.setText("Hari");

        tfnamajenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamajenisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfnopinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tftglpinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(tftglhrsbalik)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(tfterlambat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel17))
                        .addComponent(tfkddenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfnamajenis, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                        .addComponent(tftotal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfjumlahbiaya, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfnopinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tftglpinjam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tftglhrsbalik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfterlambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tfkddenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(tfnamajenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfjumlahbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENGEMBALIAN BUKU");

        tabkembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabkembali);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("ID Copy Buku");

        jLabel14.setText("Judul");

        jLabel15.setText("Status");

        tfidcopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidcopyActionPerformed(evt);
            }
        });
        tfidcopy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfidcopyKeyPressed(evt);
            }
        });

        tfjudul.setColumns(20);
        tfjudul.setRows(5);
        tfjudul.setEnabled(false);
        jScrollPane2.setViewportView(tfjudul);

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ada", "Terpinjam" }));
        cbstatus.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfidcopy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfidcopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SAVE.jpg"))); // NOI18N
        tblsave.setText("Save");
        tblsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsaveActionPerformed(evt);
            }
        });

        tblreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ITransaksi.png"))); // NOI18N
        tblreset.setText("Reset");
        tblreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblresetActionPerformed(evt);
            }
        });

        tblcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close.jpg"))); // NOI18N
        tblcancel.setText("Cancel");
        tblcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblcancelActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("ID Anggota");

        jLabel8.setText("Nama");

        tfviewnama.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfidang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfviewnama, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfidang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfviewnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tblsave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblreset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblcancel))
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tblsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblcancel)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnokembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnokembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnokembaliActionPerformed

    private void tfidcopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidcopyActionPerformed
        // TODO add your handling code here:
        //String vid_ang;
        String sql="SELECT * FROM peminjaman, copybuku WHERE peminjaman.ID_Copybuku=copybuku.ID_Copybuku and peminjaman.ID_Copybuku='"+tfidcopy.getText()+"'";
        try {
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if (rs.next()) {
                tftglpinjam.setText(rs.getString("peminjaman.Tgl_Pinjam"));
                tftglhrsbalik.setText(rs.getString("peminjaman.Tglhrskembali"));
                tfidang.setText(rs.getString("peminjaman.ID_Anggota"));
                /*vid_ang=rs.getString("Nama");
                String sql2="SELECT * FROM anggota WHERE Nama = '" + vid_ang + "'";
                try{
                    Statement stat2 = conec.createStatement();
                    ResultSet rs2 = stat2.executeQuery(sql2);
                    if(rs2.next()){               
                           tfviewnama.setText(rs2.getString(3));
                    }
                }
                    catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Terjadi kesalahan:"+e);
                    
                }*/
                tfnopinjam.setText(rs.getString("peminjaman.No_Pinjam"));
                cbstatus.setSelectedItem(rs.getString("copybuku.Statusbuku"));
                
           }
            else {
                JOptionPane.showMessageDialog(null,"No Pinjam Tidak Ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                
                tftglpinjam.setText("");
                tftglbalik.setText("");
                tfidang.setText("");
                tfnopinjam.requestFocus();
            }
            stat.close();
            carianggota();
            //carimahasiswa();
            caribuku();
        }
        catch(Exception exc){
            System.err.println("Terjadi Kesalahan : "+exc);}
        nomoran();
    }//GEN-LAST:event_tfidcopyActionPerformed

    private void tblsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsaveActionPerformed
        // TODO add your handling code here:
        String vnok  = tfnokembali.getText();
        String vtglk = tftglbalik.getText();
        String vnop  = tfnopinjam.getText();
        String vkdd  = tfkddenda.getText();
        String vto   = tftotal.getText();
        String vbuk  = tfidcopy.getText();
        
            try {
                java.sql.Statement stat = conec.createStatement();
                ResultSet data=stat.executeQuery("SELECT * FROM pengembalian WHERE No_Kembali='"+tfnokembali.getText()+"'");
                if (data.next()){
                    JOptionPane.showMessageDialog(null,"No Kembali sudah dimasukan","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                    tfnokembali.requestFocus();
                    
                }else {
                    String sql ="INSERT INTO Pengembalian VALUE('"+vnok+"','"+vtglk+"','"+vnop+"','"+vkdd+"','"+vto+"','"+vbuk+"')";
                    stat.executeUpdate(sql);
                    System.out.println(sql);
                    
                    String squ = "Update copybuku set Statusbuku='Ada' where ID_Copybuku='"+tfidcopy.getText()+"'";
                    stat.executeUpdate(squ);
                    System.out.println(squ);
                    
                    String sqq = "Update peminjaman set Statusbuku='Kembali' where No_Pinjam='"+tfnopinjam.getText()+"'";
                    stat.executeUpdate(sqq);
                    System.out.println(sqq);
                    
                    tfnokembali.setText("");
                    tftglbalik.setText("");
                    tfnopinjam.setText("");
                    tftglpinjam.setText("");
                    tftglhrsbalik.setText("");
                    tfidang.setText("");
                    tfviewnama.setText("");
                    tfidcopy.setText("");
                    tfjudul.setText("");
                    tfkddenda.setText("");
                    tfjumlahbiaya.setText("");
                    tftotal.setText("0");
                    tfterlambat.setText("");
                    tfnokembali.requestFocus();
                    //cmbdenda.setSelectedIndex(0);
                    //cmbstatus.setSelectedIndex(0);
                    tampilData();
                    time();
                    
                            
                	JOptionPane.showMessageDialog(null," Berhasil Di Simpan");
                        
		
		    tfnokembali.requestFocus();
                }
                        
                stat.close();
            }
            catch(Exception exc){
                System.err.println("Terjadi kesalahan :"+exc);
            }
        nomoran();
    }//GEN-LAST:event_tblsaveActionPerformed

    private void tblresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblresetActionPerformed
        // TODO add your handling code here:
        tfnopinjam.setText("");
        tfidang.setText("");		
        tfviewnama.setText("");
        tfnokembali.setText("");
        tftglbalik.setText("");
        tftglpinjam.setText("");
        tftglhrsbalik.setText("");
        tfidcopy.setText("");
        tfjudul.setText("");
        tfkddenda.setText("");
        tfjumlahbiaya.setText("");
        tfterlambat.setText("");
        tftotal.setText("0");
        cbstatus.setSelectedIndex(0);
        tfnamajenis.setSelectedIndex(0);
time();        
        //tfnokembali.setEnabled(true);
        //tblsave.setEnabled(true);	

        tfnokembali.requestFocus();
    }//GEN-LAST:event_tblresetActionPerformed

    private void tfterlambatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfterlambatActionPerformed
        // TODO add your handling code here:
        int hasil;
        hasil=Integer.parseInt(tfjumlahbiaya.getText())*Integer.parseInt(tfterlambat.getText());
        tftotal.setText(""+hasil);
    }//GEN-LAST:event_tfterlambatActionPerformed

    private void tfnamajenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamajenisActionPerformed
        // TODO add your handling code here:
        String sql="select * from denda where  Jenis_Denda='"+tfnamajenis.getSelectedItem()+"' order by Jenis_Denda ";
        try{
            // cbcs.removeAllItems();
            Statement stat = conec.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){
                tfkddenda.setText("");
                tfkddenda.setText(rs.getString("KD_Denda"));
                tfjumlahbiaya.setText(rs.getString("Biaya"));
                }
            //tfkddendad.setEnabled(false);
            //tfbiayad.setEnabled(false);
            //tftotald.setEnabled(true);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan:"+e);
        }
        nomoran();
    }//GEN-LAST:event_tfnamajenisActionPerformed

    private void tblcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tblcancelActionPerformed

    private void tfidcopyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfidcopyKeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            tfidcopyActionPerformed(new ActionEvent(evt.getSource(),evt.getID(),"KEY PRESS PROCESS"));
        }
    }//GEN-LAST:event_tfidcopyKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabkembali;
    private javax.swing.JButton tblcancel;
    private javax.swing.JButton tblreset;
    private javax.swing.JButton tblsave;
    private javax.swing.JTextField tfidang;
    private javax.swing.JTextField tfidcopy;
    private javax.swing.JTextArea tfjudul;
    private javax.swing.JTextField tfjumlahbiaya;
    private javax.swing.JTextField tfkddenda;
    private javax.swing.JComboBox tfnamajenis;
    private javax.swing.JTextField tfnokembali;
    private javax.swing.JTextField tfnopinjam;
    private javax.swing.JTextField tfterlambat;
    private javax.swing.JTextField tftglbalik;
    private javax.swing.JTextField tftglhrsbalik;
    private javax.swing.JTextField tftglpinjam;
    private javax.swing.JTextField tftotal;
    private javax.swing.JTextField tfviewnama;
    // End of variables declaration//GEN-END:variables

private void koneksiDatabase() {
        //throw new UnsupportedOperationException("Not yet implemented");
            try {
            Class.forName("com.mysql.jdbc.Driver");
        }
        catch(ClassNotFoundException cnf){}
        try {conec = DriverManager.getConnection("jdbc:mysql://localhost/sistemperpustakaan","root","");
        System.out.println("Koneksi Sukses");
                }
        catch(SQLException se){
            System.out.println("Koneksi Gagal : "+se);
        }
        catch(Exception e){}
}

    private void time() {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat now = new SimpleDateFormat("dd-MMM-yyyy");
        String date = now.format(cal.getTime());
        tftglbalik.setText(date);
    }

    private void tampilData() {
        Object[]Baris={"No Kembali","Tgl Kembali","No Pinjam","Kode Denda","Total"};
        DftTabMode=new DefaultTableModel(null,Baris);
        tabkembali.setModel(DftTabMode);
        String sql="select*from pengembalian";
        try {
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            int total=0;
	    while(rs.next()){
                String tnop=rs.getString("No_Kembali");
                String ttglp=rs.getString("Tgl_Kembali");
                String ttglk=rs.getString("No_Pinjam");
                String tden=rs.getString("KD_Denda");
                String tcopybk=rs.getString("Total");
                String[] data ={tnop,ttglp,ttglk,tden,tcopybk};
                DftTabMode.addRow(data);
                
            }
        }
            catch (Exception exc){
            System.err.println("Terjadi Kesalahan :"+exc);
            }
    }

    private void carianggota() {
        String sql="SELECT * FROM anggota,kartu WHERE kartu.ID_Pendaftar=anggota.ID_Pendaftar and kartu.ID_Anggota='"+tfidang.getText()+"'";
        try {
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if (rs.next()) {
                tfviewnama.setText(rs.getString("anggota.Nama"));
                
           }
            stat.close();
        }
        catch(Exception exc){
            System.err.println("Terjadi Kesalahan : "+exc);
        }
        nomoran();
    }

    private void caribuku() {
        String sql="SELECT * FROM copybuku WHERE ID_Copybuku='"+tfidcopy.getText()+"'";
        try {
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if (rs.next()) {
                tfjudul.setText(rs.getString(2));
             String status=rs.getString(3);
                /*combo set---------------------------------------------------------------------*/
                if (status.equals("Ada")){
                    cbstatus.setSelectedIndex(0);
                }

                else if (status.equals("Terpinjam")){
                    cbstatus.setSelectedIndex(1);

            }    
           
            }
            
            stat.close();
        }
        catch(Exception exc){
            System.err.println("Terjadi Kesalahan : "+exc);
        }
        nomoran();
    }

    private void jenis() {
        String al = (String) tfnamajenis.getSelectedItem();
        String ul = "select * from denda";
        
                ;
        try { 
            tfnamajenis.removeAll();
            tfnamajenis.addItem("");
            java.sql.Statement stat = conec.createStatement();
            ResultSet data=stat.executeQuery(ul);
                while (data.next()){
                   
                    tfnamajenis.addItem(data.getString(2));
                  //  as = data.getString(1);
                }
        } catch (SQLException ex) {
            System.out.println("ul "+ex);
        }
        nomoran();
    }

    private void pinjam() {
        String sql="SELECT * FROM peminjaman WHERE No_Pinjam='"+tfnopinjam.getText()+"'";
        try {
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if (rs.next()) {
                tftglpinjam.setText(rs.getString(2));
                tftglbalik.setText(rs.getString(3));
                tfidang.setText(rs.getString(4));
                tfidcopy.setText(rs.getString(5));
                String status=rs.getString(6);
                /*combo set---------------------------------------------------------------------*/
                if (status.equals("Ada")){
                    cbstatus.setSelectedIndex(0);
                }

                else if (status.equals("Terpinjam")){
                    cbstatus.setSelectedIndex(1);

            }
           }
            else {
                tfnopinjam.requestFocus();
                tftglpinjam.setText("");
                tftglbalik.setText("");
                tfidang.setText("");
            }
            }
        catch(Exception exc){
            System.err.println("Terjadi Kesalahan : "+exc);}
        nomoran();
    }

    private void nomoran() {
        String sql = "select right (No_Kembali,3) as no from pengembalian order by No_Kembali asc";
        
        try {
            Statement pst = conec.prepareStatement(sql);
            Statement stat = conec.createStatement();
            ResultSet rs = pst.executeQuery(sql);
            if (rs.first()==false)
            {
                tfnokembali.setText("K001");
            }
            else {
                rs.last();
                int no = rs.getInt(1)+1;
                String kbinasi = String.valueOf(no);
                int p_kmbinasi = kbinasi.length();
                String zero = "";
                for(int i=0; i<3-p_kmbinasi;i++){
                   // kbinasi = "0"+kbinasi;
                    zero = zero+"0";
                }
                tfnokembali.setText("K"+zero+kbinasi);
            }
            rs.close();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan:"+e);
            
        }
    }
}
